### ISSUE TITLE
Not working on contentEditable component

### ISSUE THREAD

**Issue by Dysas** [anantoghosh/react-linkify-it#12]
When I try to use react-linkify-it to wrap a contentEditable component it does not render a tag;

code example:
`<LinkItUrl>
          <LinkItEmail>
          <div  contentEditable={true} />
          </LinkItEmail>
        </LinkItUrl>`

![image](https://user-images.githubusercontent.com/33801077/160858332-b9e186b3-0890-4553-9057-43af70a3e83f.png)

**Comment by anantoghosh** [comment]
This would be out of this projects's intended use, using contenteditable with react is not straight forward.
In short if the link has to be clickable it needs to set contenteditable false for it.
https://codesandbox.io/s/react-linkify-it-forked-8mp0w3?file=/src/App.js
If you want to edit as well then you'll have to sync the dom text with react manually.
