### ISSUE TITLE
Is the special esm import needed?

### ISSUE THREAD

**Issue by Noitidart** [anantoghosh/react-linkify-it#17]
I'm using Next.js and node 14. I was trying to use that import style but it wouldn't work. I don't have the error right now but I can get it. I'm using Typescript.

I changed
```
import { LinkIt } from "react-linkify-it/dist/react-linkify-it.legacy.esm.min";
```

To:

```
import {LinkIt} from 'react-linkify-it';
```

And it started working. If not needed anymore, I would love to provide PR to remove it from readme.

**Comment by anantoghosh** [comment]
Hi,
I do not see a problem in codesandbox https://codesandbox.io/s/react-linkify-it-forked-u8vz8y?file=/src/App.js
For Next.js you should use the latter syntax only but without the error I'm not sure why it next.js won't pick up the esm.in file.

**Comment by anantoghosh** [comment]
https://codesandbox.io/s/dazzling-marco-c9bfby?file=/src/App.tsx typescript version

**Comment by Noitidart** [comment]
Thanks. So using latter means I should use `import {LinkIt} from 'react-linkify-it';` on next.js? Sorry.

**Comment by anantoghosh** [comment]
Yes.

**Comment by Noitidart** [comment]
Thanks really appreciate it. It's working great! Thanks for the lib! Should we close this?

**Comment by anantoghosh** [comment]
Sure 👍
