### ISSUE TITLE
className doesn't appear to work

### ISSUE THREAD

**Issue by drasch** [anantoghosh/react-linkify-it#6]
can't get className to pass into components. Appears to neither be a property of `LinkItUrl` nor work when specified via the `component` function per the docs.

Thanks!

**Comment by anantoghosh** [comment]
I have been busy as of late. I plan to fix it soon.

**Comment by deadcoder0904** [comment]
cool @anantoghosh, was gonna open an issue about this as well. let us know when you fix it :)

**Comment by deadcoder0904** [comment]
oh i fixed it using global config in tailwind so wouldn't need it :)

**Comment by anantoghosh** [comment]
https://codesandbox.io/s/objective-shannon-c5n82g?file=/src/App.js working demo can be seen here. Please re-open if the issue persists.
