### ISSUE TITLE
from, not form

### ISSUE THREAD

**Issue by deadcoder0904** [anantoghosh/react-linkify-it#7]
the readme contains `import` statements using `form` like:

```ts
import { LinkItUrl } form 'react-linkify-it';
```

which gives error :)

**Comment by deadcoder0904** [comment]
thanks, this works fine af :)

**Comment by anantoghosh** [comment]
🤦  I'll fix it soon.

**Comment by anantoghosh** [comment]
Fixed in v0.9.0 https://github.com/anantoghosh/react-linkify-it/releases/tag/v0.9.0.
Thanks for noticing!
